<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="72" started-at="2016-10-07T18:02:45Z" finished-at="2016-10-07T18:02:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="72" started-at="2016-10-07T18:02:45Z" finished-at="2016-10-07T18:02:45Z">
      <class name="testNGFiles.ZipCodeValidatorTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testNGFiles.ZipCodeValidatorTest@458ad742]" name="setUp" is-config="true" duration-ms="12" started-at="2016-10-07T13:02:45Z" finished-at="2016-10-07T13:02:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="InvalidZipCodeTest1()[pri:0, instance:testNGFiles.ZipCodeValidatorTest@458ad742]" name="InvalidZipCodeTest1" duration-ms="10" started-at="2016-10-07T13:02:45Z" finished-at="2016-10-07T13:02:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testNGFiles.ZipCodeValidatorTest.InvalidZipCodeTest1(ZipCodeValidatorTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidZipCodeTest1 -->
        <test-method status="FAIL" signature="InvalidZipCodeTest2()[pri:0, instance:testNGFiles.ZipCodeValidatorTest@458ad742]" name="InvalidZipCodeTest2" duration-ms="2" started-at="2016-10-07T13:02:45Z" finished-at="2016-10-07T13:02:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testNGFiles.ZipCodeValidatorTest.InvalidZipCodeTest2(ZipCodeValidatorTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidZipCodeTest2 -->
        <test-method status="PASS" signature="ValidZipCodeTest1()[pri:0, instance:testNGFiles.ZipCodeValidatorTest@458ad742]" name="ValidZipCodeTest1" duration-ms="8" started-at="2016-10-07T13:02:45Z" finished-at="2016-10-07T13:02:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidZipCodeTest1 -->
        <test-method status="PASS" signature="ValidZipCodeTest2()[pri:0, instance:testNGFiles.ZipCodeValidatorTest@458ad742]" name="ValidZipCodeTest2" duration-ms="1" started-at="2016-10-07T13:02:45Z" finished-at="2016-10-07T13:02:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidZipCodeTest2 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testNGFiles.ZipCodeValidatorTest@458ad742]" name="tearDown" is-config="true" duration-ms="1" started-at="2016-10-07T13:02:45Z" finished-at="2016-10-07T13:02:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testNGFiles.ZipCodeValidatorTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
